Repository KUSITMS-29th-TEAM-D/Frontend, pull requests merged in 2024-06, with the labels that each got.

#79 Refactor/#76/program refactor
  src/components/ExperienceDetailPage/DetailSection.tsx
  src/components/ExperienceRecommendPage/AdvertiseCarousel.tsx
  src/components/ExperienceRecommendPage/AmountBox.tsx
  src/components/ExperienceRecommendPage/AmountModal.tsx
  src/components/ExperienceRecommendPage/ExperienceRecommendTab.tsx
  src/components/ExperienceRecommendPage/RecommendBrand.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstand.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstandView.tsx
  src/components/ExperienceRecommendPage/WholeBrandView.tsx
  src/components/ExperienceRecommendPage/WholeUnderstandView.tsx
  src/components/HomePage/TesterMemberView.tsx
  src/components/MyPage/BrandView.tsx
  src/components/common/Button/AmountFilterButton.tsx
  src/components/common/Chip/PlatformChip.tsx
  src/components/common/Chip/TestChip.tsx
  src/components/common/Modal/BrandCardModal.tsx
  src/components/common/Tab/Tab.tsx
Labels: 🐞 Bug, 🔨 Refactor

#81 [HOTFIX] 라우팅 수정 및 open graph 적용
  index.html
  package.json
  src/main.tsx
  src/routers/router.tsx
  yarn.lock
Labels: 🐞 Bug

#82 v0.4.1
  index.html
  package.json
  src/main.tsx
  src/routers/router.tsx
  yarn.lock
Labels: 🐞 Bug, 🌈 Deploy

#83 fix: define 테스트 모바일 뷰 오류 수정
  src/components/DefineStartPage/DefineMobileView.tsx
  src/components/DefineTestPage/TestSection.tsx
  src/components/DefineTestPage/TestSectionTitle.tsx
  src/components/DefineTestPage/ToastMessage.tsx
  src/pages/LoadingPage.tsx
  src/styles/theme/device.ts
  src/utils/setScreenSize.ts
Labels: 🐞 Bug

#84 fix: define 테스트 모바일 뷰 오류 수정
  src/components/DefineStartPage/DefineMobileView.tsx
  src/components/DefineTestPage/TestSection.tsx
  src/components/DefineTestPage/TestSectionTitle.tsx
  src/components/DefineTestPage/ToastMessage.tsx
  src/pages/LoadingPage.tsx
  src/styles/theme/device.ts
  src/utils/setScreenSize.ts
Labels: 🐞 Bug

#85 hotfix: 스크롤 문제 해결
  src/components/DefineTestPage/TestSection.tsx
  src/pages/LoadingPage.tsx
Labels: 🐞 Bug

#86 hotfix: 로그인 후 리다이렉트 안되는 문제 해결
  vercel.json
Labels: 🐞 Bug
