Repository KUSITMS-29th-TEAM-D/Frontend, pull requests merged in 2024-05, with the labels that each got.

#11 chore: vercel.json 추가 (#10)
  vercel.json
Labels: ⚙ Chore

#15 [FEAT] 메인 홈페이지 구현
  package.json
  src/App.css
  src/assets/backgrounds/backgroundIcon3D.svg
  src/assets/cards/connector.svg
  src/assets/cards/creator.svg
  src/assets/cards/encourager.svg
  src/assets/cards/innovator.svg
  src/assets/cards/insighter.svg
  src/assets/cards/inventor.svg
  src/assets/cards/organizer.svg
  src/assets/cards/projector.svg
  src/assets/icons/arrowDown.svg
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowUp.svg
  src/assets/logos/mainLogo.svg
  src/assets/test1.png
  src/components/.gitkeep
  src/components/HomePage/BrandingSection.tsx
  src/components/HomePage/DiagnoseSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/common/Button/CarouselButton.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Carousel/index.tsx
  src/components/common/Chip.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Navigation/SideNavigation.tsx
  src/components/common/Navigation/TopNavigation.tsx
  src/components/common/SmallButton.tsx
  src/components/common/TopNavigation.tsx
  src/constants/card.ts
  src/pages/HomePage.tsx
  src/router.tsx
  src/styles/global/GlobalFont.ts
  src/styles/global/GlobalStyle.ts
  src/types/.gitkeep
  src/types/recommend.type.ts
  src/types/user.type.ts
  yarn.lock
Labels: ✨Feature

#21 [FEAT] 자기이해 홈 구현
  src/assets/backgrounds/understandCard.png
  src/components/SelfUnderstandPage/SelfUnderstandCard.tsx
  src/components/SelfUnderstandPage/SelfUnderstandView.tsx
  src/pages/SelfUnderstandPage.tsx
  src/router.tsx
Labels: ✨Feature

#19 [FEAT] Footer 구현
  src/components/common/Footer/index.tsx
  src/components/common/Layout/MainLayout.tsx
  src/pages/HomePage.tsx
  src/router.tsx
Labels: ✨Feature

#27 [FEAT] 정의하기 테스트 화면 구현
  src/assets/backgrounds/understandCard.png
  src/assets/backgrounds/understandCard1.png
  src/assets/backgrounds/understandCard2.png
  src/assets/backgrounds/understandCard3.png
  src/assets/icons/closeWhite.svg
  src/assets/icons/instagram.svg
  src/assets/icons/linkedIn.svg
  src/assets/icons/medium.svg
  src/assets/icons/naverBlog.svg
  src/assets/icons/pinterest.svg
  src/assets/icons/youtube.svg
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DefineTest/DefineChip.tsx
  src/components/DefineTest/DefineTestView.tsx
  src/components/DefineTest/DefineTextView.tsx
  src/components/DesignTest/DesignButtonView.tsx
  src/components/DesignTest/DesignChip.tsx
  src/components/DesignTest/DesignTestView.tsx
  src/components/DesignTest/DesignTextView.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/SelfUnderstandPage/SelfUnderstandCard.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Chip/TestChip.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/components/common/ProgressBar.tsx
  src/constants/defineChip.ts
  src/constants/navigation.ts
  src/pages/DefineTestPage.tsx
  src/pages/DesignTestPage.tsx
  src/router.tsx
Labels: ✨Feature

#28 [FEAT] 테스트 결과 화면 구현
  package.json
  src/assets/backgrounds/designResultBackground.png
  src/assets/cards/back/connector.png
  src/assets/cards/back/creator.png
  src/assets/cards/back/encourager.png
  src/assets/cards/back/innovator.png
  src/assets/cards/back/insighter.png
  src/assets/cards/back/inventor.png
  src/assets/cards/back/organizer.png
  src/assets/cards/back/projector.png
  src/assets/cards/connector.svg
  src/assets/cards/creator.svg
  src/assets/cards/encourager.svg
  src/assets/cards/front/connector.png
  src/assets/cards/front/creator.png
  src/assets/cards/front/encourager.png
  src/assets/cards/front/innovator.png
  src/assets/cards/front/insighter.png
  src/assets/cards/front/inventor.png
  src/assets/cards/front/organizer.png
  src/assets/cards/front/projector.png
  src/assets/cards/innovator.svg
  src/assets/cards/insighter.svg
  src/assets/cards/inventor.svg
  src/assets/cards/organizer.svg
  src/assets/cards/projector.svg
  src/assets/icons/change.svg
  src/assets/icons/download.svg
  src/components/DefineResultPage/CardSection.tsx
  src/components/DefineResultPage/DescriptionSection.tsx
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DefineTest/DefineChip.tsx
  src/components/DefineTest/DefineTestView.tsx
  src/components/DefineTest/DefineTextView.tsx
  src/components/HomePage/BrandingSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/Scrollbar/index.ts
  src/components/SelfUnderstandPage/SelfUnderstandCard.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Chip/TestChip.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/components/common/ProgressBar.tsx
  src/constants/card.ts
  src/pages/DefineResultPage.tsx
  src/pages/DefineTestPage.tsx
  src/pages/DesignResultPage.tsx
  src/pages/LoadingPage.tsx
  src/recoil/.gitkeep
  src/recoil/defineState.ts
  src/recoil/loadingState.ts
  src/router.tsx
  src/styles/theme/device.ts
  src/types/test.type.ts
  yarn.lock
Labels: ✨Feature

#31 [HOTFIX] 배포 후 이미지 에러 수정 master에 반영
  src/components/DefineResultPage/CardSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/constants/card.ts
Labels: 🐞 Bug

#32 [HOTFIX] 배포 후 이미지 에러 수정 develop에 반영
  .github/workflows/synchronize-repo.yml
  src/components/DefineResultPage/CardSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/constants/card.ts
Labels: 🐞 Bug

#34 [HOTFIX] 키워드 수정 master에 반영
  src/constants/defineChip.ts
Labels: 🐞 Bug

#33 [HOTFIX] 키워드 수정 develop에 반영
  src/constants/defineChip.ts
Labels: 🐞 Bug

#36 [FEAT] 온보딩 화면 구현
  src/apis/client.ts
  src/apis/userAPI.ts
  src/assets/backgrounds/loginBackground.png
  src/assets/backgrounds/onboardingBackground.png
  src/assets/icons/check.svg
  src/assets/icons/close.svg
  src/components/DefineResultPage/CardSection.tsx
  src/components/DefineResultPage/DescriptionSection.tsx
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DefineTest/DefineChip.tsx
  src/components/DesignTest/DesignButtonView.tsx
  src/components/DesignTest/DesignChip.tsx
  src/components/DesignTest/DesignTextView.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/LoginPage/LoginDesktopPage.tsx
  src/components/OnboardingPage/Dropdown.tsx
  src/components/OnboardingPage/ProfileSetup.tsx
  src/components/OnboardingPage/ScoreRangeBar.tsx
  src/components/OnboardingPage/Setup.style.ts
  src/components/OnboardingPage/SetupBasicInfo.tsx
  src/components/OnboardingPage/SetupBranding.tsx
  src/components/SelfUnderstandPage/SelfUnderstandView.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Chip/KeywordChip.tsx
  src/components/common/Chip/PlainChip.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownButton.tsx
  src/components/common/Dropdown/DropdownContent.tsx
  src/components/common/Input/ButtonInput.tsx
  src/components/common/Input/DefaultInput.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Layout/ResponsiveLayout.tsx
  src/components/common/Navigation/SideNavigation.tsx
  src/components/common/Navigation/TopNavigation.tsx
  src/components/common/ProgressBar/index.tsx
  src/constants/onboarding.ts
  src/hooks/useFunnel.tsx
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/OnboardingPage.tsx
  src/pages/RedirectPage.tsx
  src/recoil/onboardingState.ts
  src/routers/ExceptPreMemberRoute.tsx
  src/routers/MemberPrivateRoute.tsx
  src/routers/router.tsx
  src/services/AuthService.ts
  src/services/UserService.ts
  src/styles/global/GlobalStyle.ts
  src/types/user.type.ts
Labels: ✨Feature

#42 [FEAT] 정의하기 시작화면 구현
  src/assets/backgrounds/defineBackground.png
  src/components/DefineStartPage/DefineDesktopView.tsx
  src/components/DefineStartPage/DefineMobileView.tsx
  src/components/SelfUnderstandPage/SelfUnderstandCard.tsx
  src/pages/DefineStartPage.tsx
  src/routers/router.tsx
Labels: ✨Feature

#41 [FIX] 정의하기 결과 화면 QA 사항 반영 및 카카오 공유 기능 추가
  index.html
  src/apis/personaAPI.ts
  src/components/DefineResultPage/Button.tsx
  src/components/DefineResultPage/CardSection.tsx
  src/components/DefineResultPage/DescriptionSection.tsx
  src/components/DefineStartPage/DefineMobileView.tsx
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DefineTest/DefineChip.tsx
  src/components/common/Chip/KeywordChip.tsx
  src/constants/persona.ts
  src/pages/DefineResultPage.tsx
  src/pages/DefineTestPage.tsx
  src/pages/LoadingPage.tsx
  src/recoil/defineState.ts
  src/recoil/loadingHandlerState.ts
  src/recoil/loadingState.ts
  src/routers/router.tsx
  src/types/test.type.ts
  src/utils/kakaoShare.ts
Labels: 🐞 Bug

#44 [HOTFIX] 재배포를 위한 의미없는 코드 추가
  src/components/DefineResultPage/CardSection.tsx
Labels: 🐞 Bug

#47 v0.1.2
  src/components/DefineResultPage/CardSection.tsx
  src/components/DefineTest/DefineButtonView.tsx
Labels: 🌈 Deploy

#48 [HOTFIX] 이미지 url 수정
  src/components/DefineResultPage/CardSection.tsx
Labels: 🐞 Bug

#45 [DESIGN] 홈 화면 디자인 수정사항 반영
  src/assets/icons/define.png
  src/assets/icons/design.png
  src/assets/icons/discover.png
  src/components/HomePage/BrandingSection.tsx
  src/components/HomePage/CardCarousel.tsx
  src/components/HomePage/DiagnoseSection.tsx
  src/components/HomePage/NonMemberView.tsx
  src/components/HomePage/NonTesterMemberView.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/HomePage/TesterMemberView.tsx
  src/components/OnboardingPage/SetupBasicInfo.tsx
  src/components/OnboardingPage/SetupBranding.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownContent.tsx
  src/components/common/Dropdown/DropdownContentItem.tsx
  src/constants/onboarding.ts
  src/pages/HomePage.tsx
  src/types/recommend.type.ts
Labels: 🎨 Design

#50 [FEAT] Design 테스트 페이지 구현
  src/assets/icons/add.svg
  src/assets/icons/instagram.svg
  src/components/DesignTest/DesignButtonView.tsx
  src/components/DesignTest/DesignChip.tsx
  src/components/DesignTest/DesignTestView.tsx
  src/components/DesignTest/DesignTextView.tsx
  src/components/common/Chip/InputChip.tsx
  src/components/common/Chip/PlatformChip.tsx
  src/components/common/Layout/DefineLayout.tsx
  src/components/common/Layout/DesignLayout.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Navigation/DefineHeaderNavigation.tsx
  src/components/common/Navigation/DesignHeaderNavigation.tsx
  src/components/common/Navigation/DiscoverHeaderNavigation.tsx
  src/constants/designChip.ts
  src/routers/router.tsx
Labels: ✨Feature

#56 [FEAT] 설계하기 결과 화면
  src/apis/client.ts
  src/apis/personaAPI.ts
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DesignTest/DesignButtonView.tsx
  src/components/HomePage/NonTesterMemberView.tsx
  src/components/OnboardingPage/SetupBranding.tsx
  src/components/common/Navigation/DefineHeaderNavigation.tsx
  src/components/common/Navigation/DesignHeaderNavigation.tsx
  src/components/common/Navigation/TopNavigation.tsx
  src/constants/navigation.ts
  src/pages/DefineTestPage.tsx
  src/pages/DesignResultPage.tsx
  src/pages/DesignTestPage.tsx
  src/pages/LoadingPage.tsx
  src/pages/RedirectPage.tsx
  src/recoil/loadingState.ts
  src/routers/router.tsx
  src/services/AuthService.ts
  src/types/test.type.ts
Labels: ✨Feature

#60 v0.2.0
  src/apis/client.ts
  src/apis/personaAPI.ts
  src/assets/backgrounds/designStartBackground.png
  src/assets/icons/add.svg
  src/assets/icons/define.png
  src/assets/icons/design.png
  src/assets/icons/discover.png
  src/assets/icons/instagram.svg
  src/components/DefineTest/DefineButtonView.tsx
  src/components/DesignStartPage/DesignStartView.tsx
  src/components/DesignTest/DesignButtonView.tsx
  src/components/DesignTest/DesignChip.tsx
  src/components/DesignTest/DesignTestView.tsx
  src/components/DesignTest/DesignTextView.tsx
  src/components/HomePage/BrandingSection.tsx
  src/components/HomePage/CardCarousel.tsx
  src/components/HomePage/DiagnoseSection.tsx
  src/components/HomePage/NonMemberView.tsx
  src/components/HomePage/NonTesterMemberView.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/HomePage/TesterMemberView.tsx
  src/components/OnboardingPage/SetupBasicInfo.tsx
  src/components/OnboardingPage/SetupBranding.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Chip/InputChip.tsx
  src/components/common/Chip/PlatformChip.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownContent.tsx
  src/components/common/Dropdown/DropdownContentItem.tsx
  src/components/common/Layout/DefineLayout.tsx
  src/components/common/Layout/DesignLayout.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Navigation/DefineHeaderNavigation.tsx
  src/components/common/Navigation/DesignHeaderNavigation.tsx
  src/components/common/Navigation/DiscoverHeaderNavigation.tsx
  src/components/common/Navigation/TopNavigation.tsx
  src/constants/designChip.ts
  src/constants/navigation.ts
  src/constants/onboarding.ts
  src/pages/DefineTestPage.tsx
  src/pages/DesignResultPage.tsx
  src/pages/DesignStartPage.tsx
  src/pages/DesignTestPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoadingPage.tsx
  src/pages/RedirectPage.tsx
  src/recoil/loadingState.ts
  src/routers/router.tsx
  src/services/AuthService.ts
  src/types/recommend.type.ts
  src/types/test.type.ts
Labels: 🌈 Deploy

#58 [FEAT] 자기이해 홈 구현
  src/assets/cards/back/encourager.png
  src/assets/icons/defineBlack.png
  src/assets/icons/designBlack.png
  src/assets/icons/discoverBlack.png
  src/components/DefineResultPage/ResultView.tsx
  src/components/DesignResultPage/ResultView.tsx
  src/components/SelfUnderstandPage/DefineResultView.tsx
  src/components/SelfUnderstandPage/DesignResultView.tsx
  src/components/SelfUnderstandPage/DiscoverResultView.tsx
  src/components/SelfUnderstandPage/NoResultTemplate.tsx
  src/components/SelfUnderstandPage/TestResultSection.tsx
  src/components/common/Layout/DefineLayout.tsx
  src/components/common/Layout/DesignLayout.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Navigation/DesignHeaderNavigation.tsx
  src/components/common/Navigation/DiscoverHeaderNavigation.tsx
  src/components/common/Navigation/SideNavigation.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/constants/navigation.ts
  src/pages/DefineResultPage.tsx
  src/pages/DesignResultPage.tsx
  src/pages/SelfUnderstandPage.tsx
  src/routers/MemberPrivateRoute.tsx
  src/routers/router.tsx
  src/services/UserService.ts
Labels: ✨Feature

#52 [FEAT] 상세페이지 신청하기 섹션 구현
  src/components/ExperienceDetailPage/BubbleSection.tsx
  src/components/ExperienceDetailPage/DetailSection.tsx
  src/components/ExperienceDetailPage/ImageSection.tsx
  src/components/common/Modal/ExperienceDetailModal.tsx
  src/pages/ExperienceDetailPage.tsx
  src/routers/router.tsx
Labels: ✨Feature

#57 [FEAT] 홈 화면 API 연동
  src/apis/programAPI.ts
  src/apis/userAPI.ts
  src/components/DesignResultPage/ResultView.tsx
  src/components/HomePage/BrandingSection.tsx
  src/components/HomePage/CardCarousel.tsx
  src/components/HomePage/DiagnoseSection.tsx
  src/components/HomePage/NonMemberView.tsx
  src/components/HomePage/NonTesterMemberView.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/HomePage/TesterMemberView.tsx
  src/components/LoginPage/LoginMobilePage.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Dropdown/DropdownContent.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Modal/DefaultModal.tsx
  src/components/common/Modal/SelectAmountModal.tsx
  src/components/common/Navigation/SideNavigation.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/components/common/Navigation/TopNavigation.tsx
  src/constants/designChip.ts
  src/constants/onboarding.ts
  src/constants/persona.ts
  src/hooks/.gitkeep
  src/hooks/useDebounce.ts
  src/hooks/useGetBrandingPrograms.ts
  src/hooks/useGetBrandingProgramsNonLogin.ts
  src/hooks/useGetUnderstandingProgram.ts
  src/pages/HomePage.tsx
  src/pages/RedirectPage.tsx
  src/routers/router.tsx
  src/services/UserService.ts
  src/types/program.type.ts
  src/types/test.type.ts
  src/types/user.type.ts
Labels: ✨Feature

#64 hotfix: 유저 닉네임 저장 방식 에러 수정
  src/components/OnboardingPage/SetupBranding.tsx
  src/services/UserService.ts
Labels: 🐞 Bug

#65 [FEAT] 프로그램 상세페이지 수정 및 버블 섹션 구현
  src/apis/programAPI.ts
  src/components/DesignStartPage/DesignStartView.tsx
  src/components/ExperienceDetailPage/BubbleSection.tsx
  src/components/ExperienceDetailPage/DetailSection.tsx
  src/components/ExperienceDetailPage/ImageSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Chip/PlainChip.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Modal/DefaultModal.tsx
  src/components/common/Modal/ExperienceDetailModal.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/pages/ExperienceDetailPage.tsx
  src/routers/router.tsx
  src/styles/global/GlobalStyle.ts
  src/types/program.type.ts
Labels: ✨Feature

#66 v0.3.1
  src/apis/programAPI.ts
  src/components/DesignStartPage/DesignStartView.tsx
  src/components/ExperienceDetailPage/BubbleSection.tsx
  src/components/ExperienceDetailPage/DetailSection.tsx
  src/components/ExperienceDetailPage/ImageSection.tsx
  src/components/HomePage/PieceSection.tsx
  src/components/common/Button/PlainButton.tsx
  src/components/common/Chip/PlainChip.tsx
  src/components/common/Layout/TestLayout.tsx
  src/components/common/Modal/DefaultModal.tsx
  src/components/common/Modal/ExperienceDetailModal.tsx
  src/components/common/Navigation/TestNavigation.tsx
  src/pages/ExperienceDetailPage.tsx
  src/routers/router.tsx
  src/styles/global/GlobalStyle.ts
  src/types/program.type.ts
Labels: 🌈 Deploy

#39 [FEAT] 경험추천 홈 구현
  src/assets/advertise/advertise2.png
  src/assets/advertise/advertise3.png
  src/assets/banner.mp4
  src/assets/test2.png
  src/components/ExperienceRecommendPage/AdevertieseCard.tsx
  src/components/ExperienceRecommendPage/AdvertiseCarousel.tsx
  src/components/ExperienceRecommendPage/AmountBox.tsx
  src/components/ExperienceRecommendPage/AmountModal.tsx
  src/components/ExperienceRecommendPage/ExperienceRecommendTab.tsx
  src/components/ExperienceRecommendPage/RecommendBrand.tsx
  src/components/ExperienceRecommendPage/RecommendBrandView.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstand.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstandView.tsx
  src/components/ExperienceRecommendPage/WholeBrandSection.tsx
  src/components/ExperienceRecommendPage/WholeBrandView.tsx
  src/components/ExperienceRecommendPage/WholeUnderstandSection.tsx
  src/components/ExperienceRecommendPage/WholeUnderstandView.tsx
  src/components/common/Button/CarouselButton2.tsx
  src/components/common/Card/ExperienceCard.tsx
  src/components/common/Chip/InputChip.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Tab/Tab.tsx
  src/constants/navigation.ts
  src/pages/ExperienceRecommendPage.tsx
  src/routers/router.tsx
  src/types/experience.type.ts
  src/types/recommend.type.ts
  yarn.lock
Labels: ✨Feature

#67 v0.3.2
  src/assets/advertise/advertise2.png
  src/assets/advertise/advertise3.png
  src/assets/banner.mp4
  src/assets/test2.png
  src/components/ExperienceRecommendPage/AdevertieseCard.tsx
  src/components/ExperienceRecommendPage/AdvertiseCarousel.tsx
  src/components/ExperienceRecommendPage/AmountBox.tsx
  src/components/ExperienceRecommendPage/AmountModal.tsx
  src/components/ExperienceRecommendPage/ExperienceRecommendTab.tsx
  src/components/ExperienceRecommendPage/RecommendBrand.tsx
  src/components/ExperienceRecommendPage/RecommendBrandView.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstand.tsx
  src/components/ExperienceRecommendPage/RecommendUnderstandView.tsx
  src/components/ExperienceRecommendPage/WholeBrandSection.tsx
  src/components/ExperienceRecommendPage/WholeBrandView.tsx
  src/components/ExperienceRecommendPage/WholeUnderstandSection.tsx
  src/components/ExperienceRecommendPage/WholeUnderstandView.tsx
  src/components/common/Button/CarouselButton2.tsx
  src/components/common/Card/ExperienceCard.tsx
  src/components/common/Chip/InputChip.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/Tab/Tab.tsx
  src/constants/navigation.ts
  src/pages/ExperienceRecommendPage.tsx
  src/routers/router.tsx
  src/types/experience.type.ts
  src/types/recommend.type.ts
  yarn.lock
Labels: 🌈 Deploy

#71 [HOTFIX] QA 반영 및 라우팅 수정
  src/components/common/Footer/index.tsx
  src/routers/router.tsx
  yarn.lock
Labels: 🐞 Bug

#70 [FEAT] 마이페이지 내 페르소나 섹션 구현
  src/assets/icons/lock.svg
  src/assets/logos/brandLogo.svg
  src/assets/myPage/MypageDiscover.png
  src/components/DesignResultPage/ResultView.tsx
  src/components/DiscoverTestPage/SummaryCard.tsx
  src/components/MyPage/BrandView.tsx
  src/components/MyPage/Card.tsx
  src/components/MyPage/DateCard.tsx
  src/components/MyPage/ExperienceCard.tsx
  src/components/MyPage/MyBrandingView.tsx
  src/components/MyPage/MyExperienceView.tsx
  src/components/MyPage/MyExperienceWholeView.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/MyPage/MyUnderstandingView.tsx
  src/components/MyPage/PersonaView.tsx
  src/components/MyPage/SettingView.tsx
  src/components/common/Chip/BrandChip.tsx
  src/components/common/Modal/BrandCardModal.tsx
  src/components/common/Tab/MyPageTab.tsx
  src/pages/Mypage.tsx
  src/routers/router.tsx
  src/types/myPage.type.ts
Labels: ✨Feature

#73 [HOTFIX]
  README.md
  src/apis/client.ts
  src/assets/icons/lock.svg
  src/assets/logos/brandLogo.svg
  src/assets/myPage/MypageDiscover.png
  src/components/DesignResultPage/ResultView.tsx
  src/components/DiscoverTestPage/SpeechBox.tsx
  src/components/DiscoverTestPage/SummaryCard.tsx
  src/components/ExperienceRecommendPage/AdevertieseCard.tsx
  src/components/ExperienceRecommendPage/ExperienceRecommendTab.tsx
  src/components/HomePage/RecommendSectionTemplate.tsx
  src/components/MyPage/BrandView.tsx
  src/components/MyPage/Card.tsx
  src/components/MyPage/DateCard.tsx
  src/components/MyPage/ExperienceCard.tsx
  src/components/MyPage/MyBrandingView.tsx
  src/components/MyPage/MyExperienceView.tsx
  src/components/MyPage/MyExperienceWholeView.tsx
  src/components/MyPage/MyPageSidebar.tsx
  src/components/MyPage/MyUnderstandingView.tsx
  src/components/MyPage/PersonaView.tsx
  src/components/MyPage/SettingView.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Chip/BrandChip.tsx
  src/components/common/Modal/BrandCardModal.tsx
  src/components/common/Tab/MyPageTab.tsx
  src/constants/defineChip.ts
  src/pages/ExperienceRecommendPage.tsx
  src/pages/Mypage.tsx
  src/routers/router.tsx
  src/types/myPage.type.ts
Labels: 🌈 Deploy

#55 [FEAT] 마이 페이지 UI & 연동
  src/assets/backgrounds/setting.png
  src/assets/icons/calendar.svg
  src/assets/icons/info.svg
  src/components/MyPage/BrandView.tsx
  src/components/MyPage/Card.tsx
  src/components/MyPage/DateCard.tsx
  src/components/MyPage/MyBrandingView.tsx
  src/components/MyPage/MyExperienceWholeView.tsx
  src/components/MyPage/MyUnderstandingView.tsx
  src/components/MyPage/SettingView.tsx
  src/components/common/Modal/BrandCardModal.tsx
Labels: ✨Feature
